networks:
  wxflowaio: {}
services:
  grafana:
    container_name: grafana
    depends_on:
    - loki
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/weatherflow/weatherflow-weatherflow-overview.json
    image: grafana/grafana:latest
    networks:
      wxflowaio: null
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    restart: always
    volumes:
    - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    - ./config/grafana/dashboards:/var/lib/grafana/dashboards:ro
  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    image: grafana/loki:latest
    networks:
      wxflowaio: null
    ports:
    - protocol: tcp
      published: 3100
      target: 3100
    restart: always
    user: "${UID_GID}"
    volumes:
    - ./config/loki-config.yml:/etc/loki/loki-config.yml:ro
    - ./data/loki:/tmp/loki:rw
  weatherflow-listener:
    build:
      context: ./weatherflow-listener
    container_name: weatherflow-listener
    depends_on:
    - loki
    environment:
      WF_LOKI_URL: http://loki:3100
    networks:
      wxflowaio: null
    ports:
    - protocol: udp
      published: 50222
      target: 50222
    restart: always
version: '3.8'
